import 'package:flutter/material.dart';

import '../domain/enums.dart';

/// Icono propio de cada microhábito (contrato `Habit.icon`).
///
/// El maquetado usa nombres del set icons8 (`HABIT_ICONS` en widget_body.html);
/// aquí cada nombre se mapea a su equivalente Material. El COLOR nunca viene
/// del icono: lo pone el área (como en el maquetado, que tiñe el PNG con
/// `AREA[h.a].fg`). Nombre desconocido o nulo → icono del área.
IconData habitIconData(String? icon, HabitArea area) =>
    _byName[icon] ?? _byArea[area]!;

const Map<HabitArea, IconData> _byArea = {
  HabitArea.self: Icons.self_improvement,
  HabitArea.family: Icons.auto_stories,
  HabitArea.relationships: Icons.favorite_border,
  HabitArea.work: Icons.work_outline,
};

const Map<String, IconData> _byName = {
  // --- YO (Me) ---
  'lungs': Icons.air,
  'do-not-disturb-2': Icons.do_not_disturb_on_outlined,
  'massage': Icons.spa,
  'stretching': Icons.accessibility_new,
  'walking': Icons.directions_walk,
  'water': Icons.water_drop_outlined,
  'journal': Icons.edit_note,
  'todo-list': Icons.checklist,
  'numbered-list': Icons.format_list_numbered,
  'like--v1': Icons.thumb_up_off_alt,
  'hearts': Icons.volunteer_activism,
  'shower': Icons.shower_outlined,
  'broom': Icons.cleaning_services_outlined,
  'musical-notes': Icons.music_note_outlined,
  'spa': Icons.spa_outlined,
  'reading': Icons.menu_book_outlined,
  'apple': Icons.local_dining,
  'tea': Icons.emoji_food_beverage_outlined,
  'leg': Icons.airline_seat_legroom_extra,
  'shield': Icons.shield_outlined,
  'backpack': Icons.backpack_outlined,
  'bed': Icons.bed_outlined,
  'moon-symbol': Icons.nightlight_outlined,
  'checklist': Icons.fact_check_outlined,
  'dumbbell': Icons.fitness_center,
  'meditation-guru': Icons.self_improvement,
  'hand': Icons.back_hand_outlined,
  'idea': Icons.lightbulb_outline,
  'chat': Icons.chat_bubble_outline,
  'spa-flower': Icons.local_florist_outlined,
  // --- FAMILIA (Family) ---
  'family': Icons.family_restroom,
  'question-mark': Icons.question_mark,
  'hug': Icons.emoji_people,
  'medal': Icons.military_tech_outlined,
  't-shirt': Icons.checkroom,
  'school': Icons.school_outlined,
  'dice': Icons.casino_outlined,
  'restaurant': Icons.restaurant,
  'housekeeping': Icons.countertops_outlined,
  'healthy-food': Icons.rice_bowl,
  'open-book': Icons.auto_stories_outlined,
  'sleeping': Icons.bedtime_outlined,
  'speech-bubble': Icons.record_voice_over_outlined,
  'calendar': Icons.calendar_month_outlined,
  'teddy-bear': Icons.toys_outlined,
  'children': Icons.child_care_outlined,
  'cooking-pot': Icons.soup_kitchen_outlined,
  'note': Icons.sticky_note_2_outlined,
  'nordic-walking': Icons.nordic_walking,
  'camera': Icons.photo_camera_outlined,
  'box': Icons.inventory_2_outlined,
  'money': Icons.savings_outlined,
  'meal': Icons.dinner_dining_outlined,
  'phone': Icons.call_outlined,
  'handshake': Icons.handshake_outlined,
  'confetti': Icons.celebration_outlined,
  'hanger': Icons.dry_cleaning_outlined,
  'conference': Icons.groups_outlined,
  'gymnastics': Icons.sports_gymnastics,
  'strategy-board': Icons.alt_route,
  // --- RELACIÓN (Relationships) ---
  'sms': Icons.sms_outlined,
  'comments': Icons.question_answer_outlined,
  'thumb-up': Icons.thumb_up_outlined,
  'couple-man-woman': Icons.people_outline,
  'prayer': Icons.favorite_border,
  'spa-candle': Icons.local_fire_department_outlined,
  'friends': Icons.group_outlined,
  'megaphone': Icons.campaign_outlined,
  'picture': Icons.image_outlined,
  'clipboard': Icons.assignment_outlined,
  'microphone': Icons.mic_none,
  'teamwork': Icons.diversity_3,
  'ask-question': Icons.contact_support_outlined,
  'coffee': Icons.coffee_outlined,
  'trophy': Icons.emoji_events_outlined,
  'puzzle': Icons.extension_outlined,
  'lock': Icons.lock_outline,
  'happy': Icons.sentiment_satisfied_alt,
  'star': Icons.star_border,
  'trekking': Icons.hiking,
  'consultation': Icons.support_agent,
  'planner': Icons.event_note_outlined,
  'mail': Icons.mail_outline,
  'like': Icons.recommend_outlined,
  'dove': Icons.emoji_nature,
  'gift': Icons.card_giftcard_outlined,
  'yoga': Icons.self_improvement_outlined,
  'goal': Icons.flag_outlined,
  'kiss': Icons.favorite,
  'agreement': Icons.task_alt,
  // --- PROFESIÓN (Work) ---
  'high-priority': Icons.priority_high,
  'target': Icons.gps_fixed,
  'task': Icons.task_outlined,
  'email': Icons.forward_to_inbox_outlined,
  'desk': Icons.desktop_windows_outlined,
  'learning': Icons.psychology_outlined,
  'prize': Icons.workspace_premium_outlined,
  'help': Icons.help_outline,
  'flow-chart': Icons.account_tree_outlined,
  'rocket': Icons.rocket_launch_outlined,
  'diary': Icons.book_outlined,
  'checkmark': Icons.check_circle_outline,
  'mute': Icons.notifications_off_outlined,
  'edit': Icons.edit_outlined,
  'trash': Icons.delete_outline,
  'meeting': Icons.meeting_room_outlined,
  'notepad': Icons.note_alt_outlined,
  'water-bottle': Icons.local_drink_outlined,
  'visible': Icons.visibility_outlined,
  'chair': Icons.chair_outlined,
  'opened-folder': Icons.folder_open_outlined,
  'to-do': Icons.playlist_add_check,
  'stop-sign': Icons.pan_tool_outlined,
  'communication': Icons.connect_without_contact,
  'tasklist': Icons.list_alt_outlined,
  'inspection': Icons.manage_search,
  'delete-message': Icons.delete_sweep_outlined,
  'toolbox': Icons.home_repair_service_outlined,
  'champagne': Icons.wine_bar_outlined,
  'feedback': Icons.feedback_outlined,
};
